### PR TITLE
PR: Merge BindPadFelx Changes to Main Repo

### PR DESCRIPTION
**Pull request by notfelx**
Solved Conflicts. Create new PR to avoid issues.

...

Please note, to fix BP, I made some changes you might not want to keep, use your best judgment:
 
I changed the way the text is attributed to Inline :
```xml
<Button name="$parentTab4" inherits="PanelTopTabButtonTemplate" text="BINDPAD_TEXT_SPECIFIC_EXTRA_TAB3" id="4">
```

I changed some ENG localization text to not scale with character name as the new tabs are big an can overflow, feel free to cherry pick this change out. (I saw you made the window bigger)
```lua
BINDPAD_TEXT_SPECIFIC_TAB = "Char. Specific 1";
```

I am updating the display of the tabs in the onshow instead of the onload. (Onload was trigerring but latter overriden by something from blizz UI ? maybe a mixin/hook?). I understand OnSHow might not be best practice but it was to get the addon going at least (one call per show seems ok...).
```xml
<OnShow>
    PanelTemplates_TabResize(self, nil, nil, 36)
</OnShow>
```

I also see you made the window bigger so there's room for tabs - I will let you edit the correct sizings & positions.
image

Macros still broken - will let you dev

Felix

### CODE REVIEW

**Comment by notfelx** [comment]
Currewntly working on Macros. Made some progress: 
image

**Comment by Stanzilla** [comment]
Nice! I'll play around with the tabs some more, I like how yours are smaller but maybe a bit too small but I like the positioning of mine better which also means that we have to move the checkbox to the bottom

**Comment by notfelx** [comment]
Yeah feel free for the sizings. The highlight is messed up as well but that's a detail.

I found the root cause for macro icons and am developping a fix on one of my branches. more to follow.

**Comment by notfelx** [comment]
Working on PR to fix macro icons/edition.

image

image

**Comment by notfelx** [comment]
Still some display bugs, but I will trust you with the resizings.

image

**Comment by notfelx** [comment]
Added commits #75bc5fc and #23514fd to fix macros.

**Comment by notfelx** [comment]
image

**Comment by notfelx** [comment]
image

**Comment by notfelx** [comment]
Stopping commits on master now that my version generates no errors.
Up to you friend. I will check in now and then if you have any questions.

**Comment by Stanzilla** [comment]
@notfelx pushed a mix of yours and mine and I feel like it looks pretty nice, thank you very much!

**Comment by notfelx** [comment]
Looks Good. Closing the PR as it is not needed as-is.

**Pull request closed without merging**
